Repository testgear-tms/adapters-java, pull requests merged in 2023-05, with the labels that each got.

#14 Updated documentation.
  testgear-adapter-cucumber4/Readme.md
  testgear-adapter-cucumber5/Readme.md
  testgear-adapter-cucumber6/Readme.md
  testgear-adapter-cucumber7/Readme.md
  testgear-adapter-jbehave/Readme.md
  testgear-adapter-junit4/Readme.md
  testgear-adapter-junit5/Readme.md
  testgear-adapter-testng/Readme.md
Labels: documentation

#15 Fixed dropping the "isFlaky" flag.
  gradle.properties
  testgear-java-commons/src/main/java/io/test_gear/writers/HttpWriter.java
Labels: bug

#13 add workflow
  .github/release-drafter.yml
  .github/workflows/gradle-build.yml
  .github/workflows/gradle-publish.yml
  .github/workflows/label-verifier.yml
  .github/workflows/release-draft.yml
  build.gradle.kts
Labels: enhancement

#16 Fixed test extractExternalID_WithoutExternalID
  testgear-java-commons/src/test/java/io/test_gear/services/UtilsTest.java
Labels: enhancement
